# Controller -> index
http://localhost:8000/api/student
###

# Controller -> show
http://localhost:8000/api/student/3
###

# Controller -> destroy
DELETE http://localhost:8000/api/student/1
###

# Controller -> Update
PUT http://localhost:8000/api/student/3
Content-Type: application/json

{
"first_name": "Hello",
"last_name": "world",
"email": "hello@world.com",
"mobile_number": "00000000000"
}
###

#Controller -> create
POST http://localhost:8000/api/student
Content-Type: application/json

{
    "first_name": "Hello",
    "last_name": "world",
    "email": "hello@world.com",
    "mobile_number": "00000000000"
}
